name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.5.0'

      - name: Install dependencies
        run: npm ci

      - name: Detect Angular project
        id: project
        run: |
          PROJECT_NAME=$(jq -r '.defaultProject' angular.json)
          echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: Build Angular App
        run: |
          BASE_HREF="/${GITHUB_REPOSITORY#*/}/"
          DIST_FOLDER=$(jq -r ".projects.\"${{ steps.project.outputs.project_name }}\".architect.build.options.outputPath" angular.json)
          echo "Dist folder: $DIST_FOLDER"
          npm run build -- --output-path=$DIST_FOLDER --base-href=$BASE_HREF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.project.outputs.project_name }}
