name: Deploy Angular app to GitHub Pages

on:
  push:
    branches: ["main"]  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.5.0

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          # Detect default project name
          PROJECT_NAME=$(jq -r '.defaultProject' angular.json)
          echo "Default project: $PROJECT_NAME"
          # Get Angular build output folder (robust for Angular 17+)
          DIST_FOLDER=$(jq -r ".projects.\"$PROJECT_NAME\".targets.build.options.outputPath" angular.json)
          if [ "$DIST_FOLDER" = "null" ]; then
          DIST_FOLDER=$(jq -r ".projects.\"$PROJECT_NAME\".architect.build.options.outputPath" angular.json)
          fi
          echo "Dist folder: $DIST_FOLDER"
          # Build Angular app
          npm run build -- --configuration production --output-path=$DIST_FOLDER --base-href "/$REPO_NAME/"
          # Copy index.html to 404.html for SPA routing
          cp "$DIST_FOLDER/index.html" "$DIST_FOLDER/404.html"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: $DIST_FOLDER

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
